### ISSUE TITLE
Validate Kubernetes cluster credentials

### ISSUE THREAD

**Issue by GaneshSPatil** [gocd/kubernetes-elastic-agents#15]
as part of the validate-plugin-settings call, the plugin should:
- [ ] Validate cluster URL, username, password, and cluster ca certificate.
- [ ] Validate the kubernetes cluster is accessible using provided user's credentials.
- [ ] Validate the [rbac authorization](https://kubernetes.io/docs/admin/authorization/rbac/) rules for the provided user to make sure that the user has the minimum set of permissions on the cluster to manipulate the k8s resources.

**Comment by bdpiparva** [comment]
Closing the issue since - 

1. Cluster URL, namespace, security token and CA cert are being validated while saving plugin settings
2. Same as point 1.
3. Now we have RBAC support in helm chart itself which creates a service account for the k8s plugin. which has following permissions
   - nodes: list, get
   - events: list, watch
   - namespace: list, get
   - pods, pods/log: *
