### ISSUE TITLE
Agents are killed after 10 minutes

### ISSUE THREAD

**Issue by aamattos** [gocd/kubernetes-elastic-agents#70]
With GoCd Server 18.11 and Kubernetes plugin 2.0.0, agents are killed after 10 minutes, even when the job has not finished execution yet.

I tried to set up a timeout of 60 minutes on the Kubernetes Plugin Configuration but it does not seems to have any effect .

**Comment by GaneshSPatil** [comment]
Hey @aamattos  for us to troubleshoot this issue we would require the following from you 

1. go-server.log* files
2. gocd-kubernetes-plugin logs
3. Console snapshot of the job that was running on the K8's agent

Since these files might contain some sensitive data, we request you to share this information via an email to support@thoughtworks.com. Please refer this github issue on the email.

**Comment by aamattos** [comment]
I have just sent them.
Thanks for your help.

**Comment by GaneshSPatil** [comment]
hi @aamattos, 
Closing this issue as it was a setup issue.
